package briefing

import (
	"context"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/modu-ai/mink/internal/messaging/telegram"
	"go.uber.org/zap"
)

// TestRenderer_FanOut covers AC-007: fan-out across channels (CLI + Telegram +
// archive) renders the same semantic content. The TUI channel is exercised
// separately by TestBriefingPanel_Snapshot once the panel renderer lands.
//
// REQ-BR-002, AC-007.
func TestRenderer_FanOut(t *testing.T) {
	payload := &BriefingPayload{
		GeneratedAt: time.Date(2026, 5, 14, 7, 0, 0, 0, time.UTC),
		Status: map[string]string{
			"weather": "ok",
			"journal": "ok",
			"date":    "ok",
			"mantra":  "ok",
		},
		Weather: WeatherModule{
			Current: &WeatherCurrent{
				Temp:      18.5,
				FeelsLike: 17.0,
				Condition: "Clear",
				Location:  "Seoul",
			},
			AirQuality: &AirQuality{AQI: 45, Level: "good"},
		},
		JournalRecall: RecallModule{
			Anniversaries: []*AnniversaryEntry{
				{YearsAgo: 1, Date: "2025-05-14", EmojiMood: "🙂"},
			},
		},
		DateCalendar: DateModule{
			Today:     "2026-05-14",
			DayOfWeek: "목요일",
		},
		Mantra: MantraModule{Text: "오늘도 한 걸음"},
	}

	// (a) CLI plain rendering.
	cliText := RenderCLI(payload, true)
	if cliText == "" {
		t.Fatal("CLI render returned empty string")
	}

	// (b) Telegram rendering via stubSender to capture the dispatched request.
	stub := &stubSender{}
	cfg := TelegramChannelConfig{Token: "tkn", ChatID: 42}
	status, err := SendBriefingTelegram(context.Background(), stub, cfg, payload, zap.NewNop())
	if err != nil {
		t.Fatalf("Telegram send: %v", err)
	}
	if status != "ok" {
		t.Fatalf("Telegram status = %s, want ok", status)
	}
	if len(stub.calls) != 1 {
		t.Fatalf("Telegram calls = %d, want 1", len(stub.calls))
	}
	tgText := stub.calls[0].Text
	if stub.calls[0].ParseMode != telegram.ParseModeMarkdownV2 {
		t.Errorf("Telegram ParseMode = %s, want %s", stub.calls[0].ParseMode, telegram.ParseModeMarkdownV2)
	}

	// (c) Archive rendering. We write to a temp dir; archive uses RenderCLI(plain=true)
	// internally so the content is structurally identical to (a).
	dir := t.TempDir()
	archivePath, err := WriteArchiveToDir(dir, payload)
	if err != nil {
		t.Fatalf("Archive write: %v", err)
	}

	// Semantic equality assertions across the 3 surfaces:
	// 1. Weather core facts (temperature, condition, location, AQI)
	// 2. Journal anniversary date
	// 3. Date today + day-of-week
	// 4. Mantra text
	semanticFacts := []string{
		"Seoul",
		"Clear",
		"45",
		"2025-05-14",
		"2026-05-14",
		"목요일",
		"오늘도 한 걸음",
	}

	for _, fact := range semanticFacts {
		if !strings.Contains(cliText, fact) {
			t.Errorf("CLI render missing %q", fact)
		}
		if !strings.Contains(tgText, fact) {
			t.Errorf("Telegram render missing %q", fact)
		}
	}

	// Archive content must match CLI (it is generated by RenderCLI(plain=true)).
	for _, fact := range semanticFacts {
		// Read archive content for verification.
		// (Reading inline keeps the assertion local to the fan-out test.)
		got := readArchiveContent(t, archivePath)
		if !strings.Contains(got, fact) {
			t.Errorf("Archive content missing %q", fact)
		}
	}
}

// readArchiveContent reads the archive file produced by the fan-out test.
// Helper isolated so the assertion loop above stays compact.
func readArchiveContent(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read archive: %v", err)
	}
	return string(b)
}
