// Package insights implements Layer 3 of the Goose self-evolution pipeline.
// It aggregates trajectory data into quantitative dimensions (Overview, Models,
// Tools, Activity) and qualitative categories (Pattern, Preference, Error,
// Opportunity) with confidence scoring.
//
// @MX:ANCHOR: [AUTO] Public API boundary for the insights subsystem.
// @MX:REASON: Report, Insight, InsightCategory and InsightsPeriod are consumed
// by REFLECT-001 (Phase 5) and CLI-001. Signature changes are breaking for all
// downstream consumers.
// @MX:SPEC: SPEC-GOOSE-INSIGHTS-001
package insights

import "time"

// InsightCategory classifies qualitative insight types.
type InsightCategory int

const (
	// CategoryPattern represents repeated behavioral patterns.
	CategoryPattern InsightCategory = iota
	// CategoryPreference represents explicit or implicit user preferences.
	CategoryPreference
	// CategoryError represents failure type aggregations.
	CategoryError
	// CategoryOpportunity represents unused features or improvement potential.
	CategoryOpportunity
)

// String returns a human-readable name for the category.
func (c InsightCategory) String() string {
	switch c {
	case CategoryPattern:
		return "Pattern"
	case CategoryPreference:
		return "Preference"
	case CategoryError:
		return "Error"
	case CategoryOpportunity:
		return "Opportunity"
	default:
		return "Unknown"
	}
}

// EvidenceRef references a concrete trajectory session as evidence.
type EvidenceRef struct {
	SessionID string    `json:"session_id"`
	Timestamp time.Time `json:"timestamp"`
	// Snippet is capped at 50 chars to avoid PII re-exposure (spec.md §6.9).
	Snippet string `json:"snippet,omitempty"`
}

// Insight is a single qualitative finding with confidence and evidence.
type Insight struct {
	Category     InsightCategory `json:"category"`
	Title        string          `json:"title"`
	Description  string          `json:"description"`
	Observations int             `json:"observations"`
	Confidence   float64         `json:"confidence"`
	Evidence     []EvidenceRef   `json:"evidence"`
	// Narrative is heuristic-generated by default; LLM-generated if UseLLMSummary=true.
	Narrative string    `json:"narrative,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

// DayBucket holds a session count for a weekday (Mon-Sun).
type DayBucket struct {
	Day   string `json:"day"`
	Count int    `json:"count"`
}

// HourBucket holds a session count for an hour of day (0-23).
type HourBucket struct {
	Hour  int `json:"hour"`
	Count int `json:"count"`
}

// ActivityPattern aggregates temporal usage patterns.
// ByDay has exactly 7 elements (Mon=0 to Sun=6).
// ByHour has exactly 24 elements (0-23).
type ActivityPattern struct {
	ByDay       []DayBucket  `json:"by_day"`
	ByHour      []HourBucket `json:"by_hour"`
	BusiestDay  DayBucket    `json:"busiest_day"`
	BusiestHour HourBucket   `json:"busiest_hour"`
	ActiveDays  int          `json:"active_days"`
	MaxStreak   int          `json:"max_streak"`
}

// Overview contains aggregate quantitative metrics for a period.
type Overview struct {
	TotalSessions      int     `json:"total_sessions"`
	TotalSuccessful    int     `json:"total_successful"`
	TotalFailed        int     `json:"total_failed"`
	TotalTokens        int     `json:"total_tokens"`
	EstimatedCost      float64 `json:"estimated_cost"`
	HasFullPricing     bool    `json:"has_full_pricing"`
	TotalHours         float64 `json:"total_hours"`
	AvgSessionDuration float64 `json:"avg_session_duration"` // seconds
}

// ModelStat aggregates metrics for a single model.
type ModelStat struct {
	Model            string  `json:"model"`
	Sessions         int     `json:"sessions"`
	InputTokens      int     `json:"input_tokens"`
	OutputTokens     int     `json:"output_tokens"`
	CacheReadTokens  int     `json:"cache_read_tokens"`
	CacheWriteTokens int     `json:"cache_write_tokens"`
	TotalTokens      int     `json:"total_tokens"`
	ToolCalls        int     `json:"tool_calls"`
	Cost             float64 `json:"cost"`
	HasPricing       bool    `json:"has_pricing"`
}

// ToolStat aggregates metrics for a single tool.
type ToolStat struct {
	Tool       string  `json:"tool"`
	Count      int     `json:"count"`
	Percentage float64 `json:"percentage"` // 0-100, rounded to 2 decimals
	UsedIn     int     `json:"used_in"`    // distinct session count
}

// Report is the top-level output of InsightsEngine.Extract.
type Report struct {
	Period      InsightsPeriod                `json:"period"`
	Empty       bool                          `json:"empty,omitempty"`
	Overview    Overview                      `json:"overview"`
	Models      []ModelStat                   `json:"models"`
	Tools       []ToolStat                    `json:"tools"`
	Activity    ActivityPattern               `json:"activity"`
	Insights    map[InsightCategory][]Insight `json:"insights"`
	GeneratedAt time.Time                     `json:"generated_at"`
}
