package telegram

import (
	"errors"
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// ErrPlainTokenRejected is returned when a YAML config file contains a bot_token
// field, which violates REQ-MTGM-N01 (tokens must not be stored in plain text).
var ErrPlainTokenRejected = errors.New("telegram: bot_token field in yaml is not allowed; use keyring or env var")

// WebhookConfig holds webhook-mode-specific settings. Activated when Mode == "webhook".
type WebhookConfig struct {
	// PublicURL is the externally reachable HTTPS base URL Telegram will POST to
	// (e.g. "https://bot.example.com"). Required when Mode == "webhook".
	PublicURL string `yaml:"public_url"`

	// Secret is the hex-encoded shared secret used both as the URL path
	// component and the X-Telegram-Bot-Api-Secret-Token header. Generated by
	// setup CLI when empty.
	Secret string `yaml:"secret"`

	// ListenAddr is the local TCP address the embedded webhook server binds to
	// (e.g. ":8443"). When empty the caller-supplied mux is used (BRIDGE-001
	// integration).
	ListenAddr string `yaml:"listen_addr"`

	// FallbackToPolling determines whether webhook registration failure falls
	// back to long polling (default true). Set to false to fail fast.
	FallbackToPolling bool `yaml:"fallback_to_polling"`
}

// Config holds the Telegram channel configuration loaded from
// ~/.goose/messaging/telegram.yaml (or a custom path).
type Config struct {
	// BotUsername is the bot's @username (without @), populated during setup.
	BotUsername string `yaml:"bot_username"`

	// AllowedUsers lists the Telegram user IDs permitted to interact with the bot.
	// An empty list means no users are allowed unless AutoAdmitFirstUser is true.
	AllowedUsers []int64 `yaml:"allowed_users"`

	// Mode selects the update ingestion strategy. Valid values: "polling", "webhook".
	// Defaults to "polling" when omitted.
	Mode string `yaml:"mode"`

	// AuditEnabled controls whether inbound and outbound events are appended to
	// the AUDIT-001 log (REQ-MTGM-U01).
	AuditEnabled bool `yaml:"audit_enabled"`

	// AutoAdmitFirstUser automatically grants admin access to the first user who
	// messages the bot when AllowedUsers is empty (REQ-MTGM-S04).
	AutoAdmitFirstUser bool `yaml:"auto_admit_first_user"`

	// DefaultStreaming controls whether responses are streamed by default.
	DefaultStreaming bool `yaml:"default_streaming"`

	// SilentDefault controls whether all outbound messages are sent with
	// disable_notification=true, suppressing phone notifications for the
	// recipient (REQ-MTGM-O01). Defaults to false when omitted.
	SilentDefault bool `yaml:"silent_default"`

	// TypingIndicator controls whether BridgeQueryHandler emits
	// sendChatAction(typing) every 5 seconds while waiting for the agent
	// response, giving the user a visual "bot is typing" indicator
	// (REQ-MTGM-O02). Defaults to false when omitted.
	TypingIndicator bool `yaml:"typing_indicator"`

	// Webhook holds webhook-mode-specific configuration (REQ-MTGM-E07).
	// Used only when Mode == "webhook".
	Webhook WebhookConfig `yaml:"webhook"`
}

// rawWebhookConfig is the internal representation of the webhook section.
// FallbackToPolling uses *bool to distinguish between "not specified" (nil,
// defaults to true) and "explicitly set to false".
type rawWebhookConfig struct {
	PublicURL         string `yaml:"public_url"`
	Secret            string `yaml:"secret"`
	ListenAddr        string `yaml:"listen_addr"`
	FallbackToPolling *bool  `yaml:"fallback_to_polling"` // nil means default (true)
}

// rawConfig is the internal struct used to detect forbidden fields during parsing.
// Separating it from Config avoids exposing bot_token in the public API.
type rawConfig struct {
	BotToken           *string           `yaml:"bot_token"` // must be nil after load
	BotUsername        string            `yaml:"bot_username"`
	AllowedUsers       []int64           `yaml:"allowed_users"`
	Mode               string            `yaml:"mode"`
	AuditEnabled       bool              `yaml:"audit_enabled"`
	AutoAdmitFirstUser bool              `yaml:"auto_admit_first_user"`
	DefaultStreaming   bool              `yaml:"default_streaming"`
	SilentDefault      bool              `yaml:"silent_default"`
	TypingIndicator    bool              `yaml:"typing_indicator"`
	Webhook            *rawWebhookConfig `yaml:"webhook"`
}

// LoadConfig reads and validates the Telegram channel YAML configuration at path.
//
// It returns ErrPlainTokenRejected if the file contains a bot_token field
// (REQ-MTGM-N01). Missing files are wrapped as fs.ErrNotExist.
//
// @MX:ANCHOR: [AUTO] LoadConfig is the single config loading entry point for the telegram package.
// @MX:REASON: SPEC-GOOSE-MSG-TELEGRAM-001 N01; fan_in via bootstrap, start subcommand, tests, and future P2 wiring.
func LoadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("telegram: read config %s: %w", path, err)
	}

	var raw rawConfig
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("telegram: parse config %s: %w", path, err)
	}

	// Reject any yaml that includes a bot_token field, even if empty.
	// Storing the token in plain text violates REQ-MTGM-N01 / REQ-MTGM-U02.
	if raw.BotToken != nil {
		return nil, ErrPlainTokenRejected
	}

	cfg := &Config{
		BotUsername:        raw.BotUsername,
		AllowedUsers:       raw.AllowedUsers,
		Mode:               raw.Mode,
		AuditEnabled:       raw.AuditEnabled,
		AutoAdmitFirstUser: raw.AutoAdmitFirstUser,
		DefaultStreaming:   raw.DefaultStreaming,
		SilentDefault:      raw.SilentDefault,
		TypingIndicator:    raw.TypingIndicator,
	}

	// Apply defaults.
	if cfg.Mode == "" {
		cfg.Mode = "polling"
	}

	// Populate webhook config. FallbackToPolling defaults to true when not
	// explicitly set (nil pointer means the key was absent from yaml).
	if raw.Webhook != nil {
		cfg.Webhook.PublicURL = raw.Webhook.PublicURL
		cfg.Webhook.Secret = raw.Webhook.Secret
		cfg.Webhook.ListenAddr = raw.Webhook.ListenAddr
		if raw.Webhook.FallbackToPolling == nil {
			cfg.Webhook.FallbackToPolling = true
		} else {
			cfg.Webhook.FallbackToPolling = *raw.Webhook.FallbackToPolling
		}
	} else {
		// No webhook section: default FallbackToPolling to true.
		cfg.Webhook.FallbackToPolling = true
	}

	return cfg, nil
}

// DefaultConfigPath returns the default path for the Telegram config file.
func DefaultConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("telegram: determine home dir: %w", err)
	}
	return home + "/.goose/messaging/telegram.yaml", nil
}
