// Package scheduler — PatternReader DI seam and shared types for the daily
// PatternLearner. SPEC-GOOSE-SCHEDULER-001 P4a T-019.
package scheduler

import (
	"context"
)

// ActivityPattern is a minimal projection of insights.ActivityPattern that the
// scheduler needs for ritual-time learning. The full INSIGHTS-001 wiring lives
// in a P5+ adapter and is intentionally out of scope here, so this package does
// not import internal/learning/insights.
//
// ByHour is indexed 0..23 and counts events that fell into that local hour over
// the rolling window. DaysObserved is the number of distinct local-calendar
// days covered by the data — used to gate learner confidence (REQ-SCHED-006).
type ActivityPattern struct {
	ByHour       [24]int
	DaysObserved int
}

// PatternReader supplies an aggregated ActivityPattern over the rolling window.
// Production wiring (an InsightsEngine adapter) is intentionally deferred.
//
// @MX:NOTE: [AUTO] DI seam — production adapter wired in P5 (INSIGHTS-001 integration)
// @MX:SPEC: SPEC-GOOSE-SCHEDULER-001 REQ-SCHED-006
type PatternReader interface {
	// ReadActivityPattern returns the latest aggregated activity pattern.
	// Implementations may consult INSIGHTS-001 or any other source; callers
	// only depend on the returned shape.
	ReadActivityPattern(ctx context.Context) (ActivityPattern, error)
}

// RitualKind identifies which ritual a learner proposal applies to.
type RitualKind int

const (
	// KindMorning is the morning briefing ritual.
	KindMorning RitualKind = iota
	// KindBreakfast is the post-breakfast reminder ritual.
	KindBreakfast
	// KindLunch is the post-lunch reminder ritual.
	KindLunch
	// KindDinner is the post-dinner reminder ritual.
	KindDinner
	// KindEvening is the evening check-in ritual.
	KindEvening
)

// String returns a stable lower-case label for the ritual kind, used in log
// fields and notification payloads.
func (k RitualKind) String() string {
	switch k {
	case KindMorning:
		return "morning"
	case KindBreakfast:
		return "breakfast"
	case KindLunch:
		return "lunch"
	case KindDinner:
		return "dinner"
	case KindEvening:
		return "evening"
	default:
		return "unknown"
	}
}

// RitualTimeProposal is generated by PatternLearner when observed user activity
// drifts more than DriftThresholdMinutes from the currently configured ritual
// clock. Proposals are advisory: REQ-SCHED-019 requires explicit user
// confirmation before commit, so ConfirmRequired is always true.
type RitualTimeProposal struct {
	// Kind is the ritual the proposal applies to.
	Kind RitualKind
	// OldLocalClock is the currently configured "HH:MM" string.
	OldLocalClock string
	// NewLocalClock is the proposed "HH:MM" string after the ±2h cap is applied.
	NewLocalClock string
	// DriftMinutes is the absolute drift between OldLocalClock and the observed
	// peak hour, before the cap is applied.
	DriftMinutes int
	// SupportingDays is the number of consecutive days the observed peak hour
	// fell within ±15 min of the most recent observation. REQ-SCHED-016 requires
	// >= 3 for a committable proposal.
	SupportingDays int
	// Confidence is in [0.0, 1.0]; tied to DaysObserved at proposal time.
	Confidence float64
	// ConfirmRequired is always true (REQ-SCHED-019).
	ConfirmRequired bool
}
